start: ip

hex : "a"|"b"|"c"|"d"|"e"|"f"| "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "0"
digit :  "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
hexnum : hex hex hex hex
ipvfour : digit "." digit "." digit "." digit |   digit "." digit "." digit |  digit "." digit |  digit
ipvsix : hexnum ":"  hexnum ":"  hexnum ":"  hexnum ":"  hexnum ":"  hexnum ":"  hexnum ":"  hexnum
ip : ipvfour | ipvsix