start: value
char : "a".."z" | "A".."Z" | "0".."9"
chars : char | char chars
string: QUOTE chars QUOTE
digits: ("0".."9")+
number: ("-")? ("1".."9" digits | digits ("." digits)?)
value: object | array | string | number | "true" | "false" | "null"
array: "["  "]" | "["  list  "]"
list: value | list  ","  value
object: "{"  "}" | "{" objlist "}"
objtuple:  string  ":"  value
objlist: objtuple | objlist "," objtuple
QUOTE: "\u0022"